# Generated by Django 4.1.2 on 2023-04-24 16:45

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chirurgie', models.CharField(blank=True, choices=[('Rachis', 'Rachis'), ('Orthopedie', 'Orthopedie'), ('Viscerale', 'Viscerale'), ('Urologie', 'Urologie'), ('Thoracique', 'Thoracique'), ('Urgences', 'Urgences'), ('Neonatologie', 'Neonatologie'), ('ORL', 'ORL'), ('Ophtalmologie', 'Ophtalmologie'), ('Stomatologie', 'Stomatologie'), ('Gastroscopie', 'Gastroscopie'), ('Imagerie', 'Imagerie')], max_length=25)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('interne_suregery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interne_suregery', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Neonat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lame', models.CharField(choices=[('Oxford', 'Oxford'), ('Miller', 'Miller'), ('Macintosh', 'Macintosh')], max_length=25)),
                ('rachi', models.BooleanField(default=False)),
                ('vvp', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('interne_neonat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interne_neonat', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('echo', models.BooleanField(default=False)),
                ('prc', models.BooleanField(default=False)),
                ('deambu', models.BooleanField(default=False)),
                ('rachi', models.BooleanField(default=False)),
                ('interne_mater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interne_mater', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Complications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('spasme', models.BooleanField(default=False)),
                ('saignement', models.BooleanField(default=False)),
                ('choc', models.BooleanField(default=False)),
                ('acr', models.BooleanField(default=False)),
                ('interne_complication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interne_complication', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BasicMoves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfusion', models.CharField(choices=[('main', 'main'), ('saphène', 'saphène')], max_length=25)),
                ('voie_aerienne', models.CharField(choices=[('Masque Facial', 'Masque Facial'), ('Masque Laryngé', 'Masque Laryngé'), ('Intubation', 'Intubation')], max_length=25)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('interne_moves', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interne_moves', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ALR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloc', models.CharField(choices=[('Rachianesthesie', 'Rachianesthesie'), ('Péridurale', 'Péridurale'), ('Caudale', 'Caudale'), ('Bloc maxillaire', 'Bloc maxillaire'), ('Pudendal Neurostim', 'Pudendal Neurostim'), ('Pudendal Echo', 'Pudendal Echo'), ('Ilioinguinal', 'Ilioinguinal'), ('Penien', 'Penien')], max_length=25)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('interne_alr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interne_alr', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
