# Generated by Django 4.1.2 on 2023-04-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicmoves',
            name='perfusion',
            field=models.CharField(choices=[('Main', 'Main'), ('Saphène', 'Saphène')], max_length=25),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='chirurgie',
            field=models.CharField(blank=True, choices=[('Rachis', 'Rachis'), ('Orthopedie', 'Orthopedie'), ('Viscerale', 'Viscerale'), ('Urologie', 'Urologie'), ('Thoracique', 'Thoracique'), ('Urgences', 'Urgences'), ('Neonatologie', 'Neonatologie'), ('ORL', 'ORL'), ('Ophtalmologie', 'Ophtalmologie'), ('Stomatologie', 'Stomatologie'), ('Gastro', 'Gastro'), ('Imagerie', 'Imagerie')], max_length=25),
        ),
    ]
