# Generated by Django 4.1.2 on 2023-04-24 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ARbook', '0002_alter_basicmoves_perfusion_alter_surgery_chirurgie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surgery',
            old_name='interne_suregery',
            new_name='interne_surgery',
        ),
    ]
