# Generated by Django 4.1.2 on 2023-04-24 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ARbook', '0003_rename_interne_suregery_surgery_interne_surgery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basicmoves',
            old_name='interne_moves',
            new_name='interne',
        ),
        migrations.RenameField(
            model_name='surgery',
            old_name='interne_surgery',
            new_name='interne',
        ),
    ]
