# Generated by Django 4.1.2 on 2023-04-24 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ARbook', '0004_rename_interne_moves_basicmoves_interne_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alr',
            old_name='interne_alr',
            new_name='interne',
        ),
        migrations.RenameField(
            model_name='complications',
            old_name='interne_complication',
            new_name='interne',
        ),
        migrations.RenameField(
            model_name='mater',
            old_name='interne_mater',
            new_name='interne',
        ),
        migrations.RenameField(
            model_name='neonat',
            old_name='interne_neonat',
            new_name='interne',
        ),
    ]
