# Generated by Django 4.1.2 on 2023-04-24 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARbook', '0005_rename_interne_alr_alr_interne_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alr',
            name='bloc',
            field=models.CharField(blank=True, choices=[('Rachianesthesie', 'Rachianesthesie'), ('Péridurale', 'Péridurale'), ('Caudale', 'Caudale'), ('Bloc maxillaire', 'Bloc maxillaire'), ('Pudendal Neurostim', 'Pudendal Neurostim'), ('Pudendal Echo', 'Pudendal Echo'), ('Ilioinguinal', 'Ilioinguinal'), ('Penien', 'Penien')], max_length=25),
        ),
        migrations.AlterField(
            model_name='basicmoves',
            name='perfusion',
            field=models.CharField(blank=True, choices=[('Main', 'Main'), ('Saphène', 'Saphène')], max_length=25),
        ),
    ]
