# Generated by Django 4.1.2 on 2023-05-06 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ARbook', '0007_user_is_interne_alter_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(blank=True, choices=[('< 1 mois', '< 1 mois'), ('< 1 an', '< 1 an'), ('< 3 ans', '< 3ans'), ('< 10 ans', '< 10 ans')], max_length=25)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('interne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interne_age', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
