# Generated by Django 4.1.2 on 2023-05-06 20:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ARbook', '0008_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complications',
            name='acr',
        ),
        migrations.RemoveField(
            model_name='complications',
            name='choc',
        ),
        migrations.RemoveField(
            model_name='complications',
            name='saignement',
        ),
        migrations.RemoveField(
            model_name='complications',
            name='spasme',
        ),
        migrations.AddField(
            model_name='complications',
            name='complication',
            field=models.CharField(choices=[('Spasme', 'Spasme'), ('Choc', 'Choc'), ('Saignement', 'Saignement'), ('ACR', 'ACR')], default=django.utils.timezone.now, max_length=25),
            preserve_default=False,
        ),
    ]
