# Generated by Django 4.1.2 on 2023-05-06 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ARbook', '0009_remove_complications_acr_remove_complications_choc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mater',
            old_name='deambu',
            new_name='Deambulatoire',
        ),
        migrations.RenameField(
            model_name='mater',
            old_name='echo',
            new_name='Echoreperage',
        ),
        migrations.RenameField(
            model_name='mater',
            old_name='prc',
            new_name='PRC',
        ),
        migrations.RenameField(
            model_name='mater',
            old_name='rachi',
            new_name='Rachi',
        ),
    ]
