# Generated by Django 4.1.2 on 2023-05-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARbook', '0010_rename_deambu_mater_deambulatoire_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mater',
            name='Deambulatoire',
        ),
        migrations.RemoveField(
            model_name='mater',
            name='Echoreperage',
        ),
        migrations.RemoveField(
            model_name='mater',
            name='PRC',
        ),
        migrations.RemoveField(
            model_name='mater',
            name='Rachi',
        ),
        migrations.AddField(
            model_name='mater',
            name='mater',
            field=models.CharField(blank=True, choices=[('Echorepérage', 'Echorepérage'), ('Péri-Rachi combinée', 'Péri-Rachi combinée'), ('Déambulatoire', 'Déambulatoire'), ('Rachianesthésie', 'Rachianesthésie')], max_length=25),
        ),
        migrations.AlterField(
            model_name='complications',
            name='complication',
            field=models.CharField(blank=True, choices=[('Spasme', 'Spasme'), ('Choc', 'Choc'), ('Saignement', 'Saignement'), ('ACR', 'ACR')], max_length=25),
        ),
        migrations.AlterField(
            model_name='neonat',
            name='rachi',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='neonat',
            name='vvp',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
