# Generated by Django 4.1.2 on 2023-05-07 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARbook', '0011_remove_mater_deambulatoire_remove_mater_echoreperage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicmoves',
            name='voie_aerienne',
            field=models.CharField(blank=True, choices=[('Masque Facial', 'Masque Facial'), ('Masque Laryngé', 'Masque Laryngé'), ('Intubation', 'Intubation')], max_length=25),
        ),
    ]
