# Generated by Django 4.1.2 on 2023-05-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARbook', '0012_alter_basicmoves_voie_aerienne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neonat',
            name='lame',
            field=models.CharField(blank=True, choices=[('Oxford', 'Oxford'), ('Miller', 'Miller'), ('Macintosh', 'Macintosh')], max_length=25),
        ),
    ]
